### PR TITLE
Update Readme to add known limitations and conform developer notes to contributing guide

### PR DESCRIPTION
**Pull request by QuintinWillison**

### CODE REVIEW

**Comment by kavalerov** [comment]
@QuintinWillison one note is that things there are going to be included in the next release are not in the list of the Known Limitations - should we add them, or should this list reflect the state of the repo itself => than the current list is correct?

**Review by kavalerov — CHANGES_REQUESTED** [review]
@QuintinWillison i looked at this again and there are 2 things that still need addressing:
1. We can remove the "Developer Preview" section as all the known limitations are listed 

2. If there is no special reason for the current location of Known Limitations section, can we please move it up to right after the Supported Platforms section, similar to https://github.com/ably/ably-cocoa ? Until we have a proper template for readmes, let's still try to make them similar in structure.

**Review by tiholic — APPROVED** [review]

**Review by mattheworiordan — CHANGES_REQUESTED** [review]
@QuintinWillison can we include a link to the documentation for the SDK please?  I appreciate we have a link to the quick start guide, but that is wholly different to "Here are the docs for this SDK", which I think is beneficial for any user arriving/

**Review by mattheworiordan — COMMENTED** [review]
In fact, looking at https://github.com/ably/ably-ruby for example, we should ideally be introducing a lot of the common elements we have in other READMEs.

1. An intro that provides links back to Ably
2. Indicators of the bersion (if that exists for the Flutter ecosystem)
3. Heading for Documentation + link to relevant docs.
4. Using the API code examples structured based on core features.
5. Support information

@tbedford I know you have mentioned standardising this before.  I believe this is a good opportunity to move forward with that, even if only to standardise on what we have.

**Comment by mattheworiordan** [comment]
I noted a few inconistencies that needed addressing the existing README so did a quick PR at https://github.com/ably/ably-ruby/pull/239.  I hope that helps.

**Comment by QuintinWillison** [comment]
This pull request is at risk of becoming a never ending story. I'm going to land it in its current state as it is already a marked improvement. We'll address @mattheworiordan's comments under the issue I've just created, #113.

**Comment by mattheworiordan** [comment]
> We'll address @mattheworiordan's comments under the issue I've just created, #113.

Ok, who is picking that issue up @QuintinWillison?

**Pull request merged**
