### PR TITLE
Release 1.2.14 (patch to original release PR)

### PR DESCRIPTION
**Pull request by ikurek**
The version bump and all changes were made in #393 but the release failed, due to Flutter 3 issues. This PR only updates the CHANGELOG file to include latest changes.

### CODE REVIEW

**Review by QuintinWillison — CHANGES_REQUESTED** [review]
Lines referring to CI, test dependencies or otherwise fixing tests, all don't have customer-facing value so should not be included in the change log.

**Comment by QuintinWillison** [comment]
☝️ akin to my comment on the original release PR for `1.2.14`: https://github.com/ably/ably-flutter/pull/393#pullrequestreview-972418539

**Comment by ikurek** [comment]
@QuintinWillison Sorry, I thought we may want to include things related to test or dependencies (since they're part of the package) and only skip internal changes to the library. I've removed the entries you mentioned 🙂

**Review by QuintinWillison — APPROVED** [review]

**Comment by ikurek** [comment]
I had to update from `main` to merge, so I added one more changelog entry in https://github.com/ably/ably-flutter/pull/406/commits/00ccd8f5b303a737d4b667a69bb633aaf8f3ac68

**Pull request merged**
